# Generated by Django 3.1 on 2020-08-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('eidtion_year', models.IntegerField()),
                ('designer', models.CharField(max_length=30)),
                ('game_duration_min', models.IntegerField()),
                ('player_number', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Regular'), (4, 'Good'), (5, 'Very good')])),
                ('played', models.BooleanField()),
                ('acquisition_date', models.DateField()),
            ],
        ),
    ]
